export const ROUTES = {
  home: '/',
  login: '/login',
  setupPassword: '/setup/password',
  setupTwoFactor: '/setup/two-factor',
  profile: '/profile',
  events: '/events',
  extraServices: '/extra-services',
  clients: '/clients',
  halls: '/halls',
  menu: '/menu',
  gallery: '/gallery',
  showcase: '/showcase',
  showcaseMenu: '/showcase/menu',
  finance: '/finance',
  warehouse: '/warehouse',
  shopping: '/shopping',
  workers: '/workers',
  users: '/users',
  roles: '/roles',
  auditLogs: '/audit-logs',
} as const;
